### ISSUE TITLE
Performance and only the largest ROI

### ISSUE THREAD

**Issue by schmiedc** [BIOP/ijp-max-inscribed-circles#1]
Hi Olivier,

I tried your plugin. Very nice by the way :) 
I have relatively large images 1388x1040px with large irregular shaped objects in them. 
I would like to calculate the largest inscribed circle. So I would like to use the following function:
"Setting the Minimum Disk Diameter to 0 will return a single ROI with the largest inscribed circle."

When I do that I noticed 2 things: 
1. setting 0 does not give you a single ROI as advertised ;) . It give you still a lot of ROIs. 
2. it takes ages (many many minutes, super bad since I have lots of images ;) ) to calculated as opposed to setting a threshold of lets say 1 px. 

Maybe the first is a bug or can I do something wrong here?
For the second problem. Would it not be good to combine the option of only getting one ROI with a sensible Minimum Disk Diameter as a lower threshold? Would improve the performance in my eyes. 
So you could for example, set the option of getting only the largest inscribed circle as a checkbox.

I can deal with the selection of the largest ROI later on in the analysis... but would be nice to have that from the get go :) 

Thanks a lot!
Christopher

**Comment by lacan** [comment]
Hi Christopher!

Glad you are using it! Indeed there was a bug there, but I have fixed it now if you grab it from our update site or get it from here, you should only get a single ROI when setting the diameter to 0.0

**Comment by schmiedc** [comment]
Hi :) 
its fixed! Also it is much faster now ;) I looked at the output ROI now in more detail. The circle is outside the object like so:
![screen shot 2017-07-05 at 16 56 07](https://user-images.githubusercontent.com/10744409/27870411-112e55a0-61a3-11e7-814d-d6a7b95e5588.png)
Is this acceptable behaviour? 

Thank you :) 
Cheers,
Christopher

**Comment by lacan** [comment]
Strange. 

I have changed the code to take care of such offsets. 
Keep in mind however that as we are using a pixel mask and distance map to compute the circles, an error of ~1px cam be expected.

I have bumped the version and also updated the POM to the new SciJava one and uploaded it to our PTBIOP update site. 

Let me know if this works better for you!
Oli

**Comment by schmiedc** [comment]
Hi :) 

thanks a lot for the quick response. 
Looks much better now, I guess it was just visually distracting. It is also not vital since you specified that 1px error is expected and I guess on size of the objects I measure this is negligible. 

All works nice! You are the best! 

Cheers,
Christopher
