### ISSUE TITLE
Min diameter

### ISSUE THREAD

**Issue by Semple-bio** [BIOP/ijp-max-inscribed-circles#4]
Good day.
In the new version of the plugin there is a hard coded minimum diameter of 1+. Previously this value had to be set at 0 to force only 1, max sized circle inscription. Now all my macros are just throwing errors.
What is the new way for the previous behaviour?

**Comment by lacan** [comment]
Dear @Semple-bio , 

I had forgotten about this functionality. Hopefully the update fixes it. See #5
